extends RefCounted
class_name EventType


const COUNTRY_SELECTED: StringName = &"countrySelected"
const ARMY_SELECTED: StringName = &"armySelected"
const ARMY_MOVE_STARTED: StringName = &"armyMoveStarted"
const ARMY_MOVED: StringName = &"armyMoved"
const UNITS_RECRUITED: StringName = &"unitsRecruited"
const ARMY_CREATED: StringName = &"armyCreated"
const ARMY_UPDATED: StringName = &"armyUpdated"
const BATTLE_STARTED: StringName = &"battleStarted"
const BATTLE_ENDED: StringName = &"battleEnded"
const COUNTRY_CONQUERED: StringName = &"countryConquered"
const NOT_ENOUGH_GOLD: StringName = &"notEnoughGold"
const INVALID_ATTACK: StringName = &"invalidAttack"
const UPGRADE_CHOICE_OPENED: StringName = &"upgradeChoiceOpened"
const UPGRADE_CHOSEN: StringName = &"upgradeChosen"
const THREAT_CHANGED: StringName = &"threatChanged"
const WORLD_REACTION_UPDATED: StringName = &"worldReactionUpdated"
const MINI_GOAL_REWARD_CLAIMED: StringName = &"miniGoalRewardClaimed"
const META_PROGRESS_CHANGED: StringName = &"metaProgressChanged"
const META_UPGRADE_PURCHASED: StringName = &"metaUpgradePurchased"
const CROWNS_REWARDED: StringName = &"crownsRewarded"
const MISSILE_LAUNCHED: StringName = &"missileLaunched"
const RUN_STARTED: StringName = &"runStarted"
const RUN_RESET: StringName = &"runReset"
const RUN_WON: StringName = &"runWon"
const GAME_SPEED_CHANGED: StringName = &"gameSpeedChanged"
const MONTH_TICK: StringName = &"monthTick"
